"""Provider configuration definitions.

Central registry of all LLM provider configurations with:
- Endpoint URLs
- Authentication requirements
- Model lists
- Rate limit information
"""

from providers.base import (
    AuthType,
    ProviderConfig,
    ProviderCapability,
)
from providers.model_capabilities import (
    groq_models,
    cerebras_models,
    mistral_models,
    openrouter_models,
    cloudflare_models,
    kilo_models,
    llm7_models,
    huggingface_models,
    google_models,
)


# Provider configurations
PROVIDER_CONFIGS = {
    "google": ProviderConfig(
        name="google",
        display_name="Google AI Studio",
        endpoint="https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        auth_type=AuthType.REQUIRED,
        auth_env_var="GOOGLE_API_KEY",
        default_models=[google_models[0], google_models[1]],
        all_models=google_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
        ],
        requires_auth=True,
        anonymous_access=None,
        rate_limit_info="Varies by model, see Google AI Studio docs",
    ),
    "groq": ProviderConfig(
        name="groq",
        display_name="Groq",
        endpoint="https://api.groq.com/openai/v1/chat/completions",
        auth_type=AuthType.REQUIRED,
        auth_env_var="GROQ_API_KEY",
        default_models=[groq_models[0], groq_models[1]],
        all_models=groq_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
        ],
        requires_auth=True,
        anonymous_access=None,
        rate_limit_info="100k TPM, 60 RPM",
    ),
    "cerebras": ProviderConfig(
        name="cerebras",
        display_name="Cerebras",
        endpoint="https://api.cerebras.ai/v1/chat/completions",
        auth_type=AuthType.REQUIRED,
        auth_env_var="CEREBRAS_API_KEY",
        default_models=[cerebras_models[0], cerebras_models[1]],
        all_models=cerebras_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
        ],
        requires_auth=True,
        anonymous_access=None,
        rate_limit_info="100k TPM, 60 RPM",
    ),
    "mistral": ProviderConfig(
        name="mistral",
        display_name="Mistral AI",
        endpoint="https://api.mistral.ai/v1/chat/completions",
        auth_type=AuthType.REQUIRED,
        auth_env_var="MISTRAL_API_KEY",
        default_models=[mistral_models[0], mistral_models[1]],
        all_models=mistral_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
        ],
        requires_auth=True,
        anonymous_access=None,
        rate_limit_info="100k TPM, 60 RPM",
    ),
    "openrouter": ProviderConfig(
        name="openrouter",
        display_name="OpenRouter",
        endpoint="https://openrouter.ai/api/v1/chat/completions",
        auth_type=AuthType.REQUIRED,
        auth_env_var="OPENROUTER_API_KEY",
        default_models=[openrouter_models[0], openrouter_models[1]],
        all_models=openrouter_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
            ProviderCapability.CONTEXT_EXTENSION,
        ],
        requires_auth=True,
        anonymous_access=None,
        rate_limit_info="100k TPM, 60 RPM",
    ),
    "cloudflare": ProviderConfig(
        name="cloudflare",
        display_name="Cloudflare Workers AI",
        endpoint="https://api.cloudflare.com/client/v4/cd/ai/v1",
        auth_type=AuthType.REQUIRED,
        auth_env_var="CLOUDFLARE_API_KEY",
        default_models=[cloudflare_models[0], cloudflare_models[1]],
        all_models=cloudflare_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
        ],
        requires_auth=True,
        anonymous_access=None,
        rate_limit_info="100k TPM, 60 RPM",
    ),
    "kilo": ProviderConfig(
        name="kilo",
        display_name="Kilo",
        endpoint="https://api.kilo.ai/v1/chat/completions",
        auth_type=AuthType.OPTIONAL,
        auth_env_var="KILO_API_KEY",
        default_models=[kilo_models[0]],
        all_models=kilo_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
        ],
        requires_auth=False,
        anonymous_access="limited",
        rate_limit_info="10k TPM, 20 RPM (unauthenticated)",
    ),
    "llm7": ProviderConfig(
        name="llm7",
        display_name="LLM7",
        endpoint="https://api.llm7.ai/v1/chat/completions",
        auth_type=AuthType.OPTIONAL,
        auth_env_var="LLM7_API_KEY",
        default_models=[llm7_models[0], llm7_models[1]],
        all_models=llm7_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
            ProviderCapability.FUNCTION_CALLING,
            ProviderCapability.STREAMING,
        ],
        requires_auth=False,
        anonymous_access="limited",
        rate_limit_info="10k TPM, 20 RPM (unauthenticated)",
    ),
    "huggingface": ProviderConfig(
        name="huggingface",
        display_name="HuggingFace Router",
        endpoint="https://api-inference.huggingface.co/models",
        auth_type=AuthType.OPTIONAL,
        auth_env_var="HUGGINGFACE_API_KEY",
        default_models=[huggingface_models[0], huggingface_models[1]],
        all_models=huggingface_models,
        supports=[
            ProviderCapability.CHAT,
            ProviderCapability.JSON_MODE,
        ],
        requires_auth=False,
        anonymous_access="limited",
        rate_limit_info="1k TPM, 5 RPM (unauthenticated)",
    ),
}